name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - flake.lock
      - flake.nix
      - nix/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - flake.lock
      - flake.nix
      - nix/**

permissions:
  contents: read

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: prepare flake on ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - arm
        include:
          - arch: x86
            runner: ubuntu-26.04
            system: x86_64-linux
          - arch: arm
            runner: ubuntu-26.04-arm
            system: aarch64-linux

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: true
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@v14
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
          use-gha-cache: true
      - name: Evaluate flake
        run: nix flake check --no-build --all-systems
      - name: Prepare package and VMs
        run: |
          nix build --no-link -L \
            ".#checks.${{ matrix.system }}.vm" \
            ".#checks.${{ matrix.system }}.upstream.driver"

  test:
    name: test flake on ${{ matrix.arch }} (${{ matrix.shard }}/8)
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - arm
        shard:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
        include:
          - arch: x86
            runner: ubuntu-26.04
            system: x86_64-linux
          - arch: arm
            runner: ubuntu-26.04-arm
            system: aarch64-linux

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: true
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@v14
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
          use-gha-cache: true
      - name: Run upstream Linux shard
        run: nix build --no-link -L ".#checks.${{ matrix.system }}.upstream-${{ matrix.shard }}"
